### ISSUE TITLE
Force logout

### ISSUE THREAD

**Issue by hijackHarry** [ProfileCreator/ProfileCreator#185]
Hello all!  great app her and thanks for all in advance.  I have set up the auto logout feature with profile creator.  However how can I force logout a user when they have unsaved work open?  Any ideas?  Did I miss a step?  Thank you! #

**Comment by apizz** [comment]
@hijackHarry Thanks for your question.

This is more of a macOS thing than a ProfileCreator thing.  I know there are a lot of people in the Mac Admin community that have tried to implement a way to address this precise issue when they have a profile configured to auto logout users have a period of inactivity.

Unfortunately, macOS doesn't have a native mechanism for doing this.  There are tools like [auto_logout.py](https://github.com/sheagcraig/auto_logout) but because the built-in `shutdown` and `restart` commands require admin privileges, this requires updating the sudoers file, which offers it's own challenges as far as management & deployment go.

This [discussion on Jamfnation](https://www.jamf.com/jamf-nation/discussions/31699/auto-logout) may also be helpful.  I like the idea of having a policy triggered at logout, but I would want to be able to verify if another session is detected before offering a restart.

Haven't personally gone this route, so can't make a recommendation from experience, but every couple of months I'm reminded of this and never ultimately have the time or overwhelming need to implement a solution.  We already have a weekly policy that runs from our MDM early in the morning on all our lab desktops to forcibly reboot them.

Maybe I'll finally get around to this ...

**Comment by apizz** [comment]
@hijackHarry you got me going down a rabbit hole, hehe ...

I did a lot of testing on this today, and ultimately found it was easier to force a machine reboot, rather than try to kill just the loginwindow process of the still logged in user.

The use case I imagined is (assuming multi-user sessions are allowed from the lock screen) a user who stumbles on a machine where another user didn't log out clicks the "Switch User" button in order to login.  Once this second user is done, they _should_ logout (thereby indicating they are done using the machine).  It's that action which I have trigger the script to check how many loginwindow processes are active and force reboot, if more than 1.

![SwitchUser](https://user-images.githubusercontent.com/11789931/65725225-20aaa200-e080-11e9-9aef-b4786a5c751b.png)

Certainly not _perfect_ but I guess I'll sleep a little better now.

```
#!/bin/bash

# Determine loginwindow processes running and reboot the machine if
# more than 1 is detected.

USER=$(/usr/sbin/scutil <<< "show State:/Users/ConsoleUser" | /usr/bin/awk -F': ' '/[[:space:]]+Name[[:space:]]:/ { if ( $2 != "loginwindow" ) { print $2 }}')
# Searches for loginwindow processes and calculates the number running
LOGIN_PROCESSES=$(/usr/bin/pgrep loginwindow)
COUNTLOGINS=$(/bin/echo "$LOGIN_PROCESSES" | /usr/bin/wc -l | /usr/bin/sed 's/ //g')
LOG="/Library/Logs/ForceLogout.log"
P_OWNER=()

writelog () {
	/bin/echo "${1}"
	/bin/echo $(/bin/date) "${1}" >> $LOG
}

# If number of loginwindow process is greater than 1, runs the script
if [ "$COUNTLOGINS" -gt "1" ]; then
	writelog "Multiple logins detected. Running script ..."
else
	writelog "Only 1 user detected. Exiting."
	exit 0
fi

for ((i = 0; i < ${#LOGIN_PROCESSES[@]}; i++)); do
	# Get the loginwindow process owner given the pid and write to array
	P_OWNER+=($(/bin/ps -eo user,pid | /usr/bin/grep -w "${LOGIN_PROCESSES[$i]}" | /usr/bin/awk '{print $1}'))
done

for ((i = 0; i < ${#LOGIN_PROCESSES[@]}; i++)); do
	# If process owner is not the current active user OR root, reboot the machine
	if [ "${P_OWNER[$i]}" != "$USER" ] && [ "${P_OWNER[$i]}" != "root" ]; then
		# Force reboot machine
		writelog "Rebooting to clear logged in user ${P_OWNER[$i]} ..."
		/sbin/shutdown -r now
	fi
done

exit
```
