### ISSUE TITLE
VPN Payload?

### ISSUE THREAD

**Issue by PhillyPhoto** [ProfileCreator/ProfileCreator#239]
It looks like it was requested in issue #54, but was closed without being added.

I manually added our VPN payload to a network profile, and imported it to PC, but after signing and uploading it to Jamf and installing the profile, the VPN connection doesn't exist on the device. 

The other payloads such as AD certificate, WiFi, Ethernet, etc that were created in PC work fine.

**Comment by apizz** [comment]
https://github.com/ProfileCreator/ProfileManifests/pull/358

The problem is the VPN payload is very complex, and as Apple has written it ProfileCreator can't handle this.  The payload is in iMazing Profile Editor, so feel free to use it there.  I was trying to get it working in ProfileCreator but haven't had time to revisit.

**Comment by PhillyPhoto** [comment]
@apizz I'll look into the iMazing Profile Editor. Thanks!
