### ISSUE TITLE
Feature Idea: Search and Import Community maintained Profiles

### ISSUE THREAD

**Issue by aschwanb** [ProfileCreator/ProfileCreator#47]
One of the things that make autopkg great is the way it allows individuals to commit their own recipes (and find recipes of others) without having to change the app itself. I don't know how hard this would be to achieve in swift, but have you thought of a way users can maintain their own profiles and offer them to the community?

Let's use menu.nomad.login.ad as an example. Maybe users could subscribe to a repo containing the profile and every time a new key is added, ProfileCreator would detect the change and update the reference in the app.

I'm aware that this would add some complexity, but it would allow ProfileCreator to focus on a set of core profiles to maintain (probably the macOS/iOS ones) vs patching every change in every supported profile.

**Comment by rodchristiansen** [comment]
Fanatastic idea. I have a lot of manually created profiles that the community can benefit from.

**Comment by erikberglund** [comment]
That is a great idea, and I have had the same idea since I started the application. It's great that both of these ideas, that are two separate things basically, Is what I'm working towards.

The goal of this application IS to be community supported, or else it will not live long as I can't keep it up myself.  But there are also a lot of things I would like to improve over the autopkg way of handling user manifests.

Preferably I would like to only have one version of a specific manifest, and I would like everyone to contribute to the same manifests to make make it an issue to have the "right" or most updated version of a payload. But there is also the issue of how to search or find them if they are user repositories. You can't search GitHub unless the repository is included in another repository like autopkg does it. That is a limitation I would like to avoid. As it is now, anyone can fork and contribute to the current manifest repository, that would be the best solution. Only one place where everyone is helping out with.

But, I also recognize the need for more private manifests for enterprise applications etc, and that also need to be handled.

Today, the app is programmed to look in two locations for manifests. In the app bundle, or in "~/Library/Application Support/ProfileCreator/<FolderName>". So currently you can place manifests there, but if they are "overrides" or share the same domain the result is undefined.

For the next beta release I'm working on fixing that, I've added a pre-commit script that always will update the manifest version on any commit to the manifest. And I've added an index file that contains all current files, versions, and hashes to make it easier to single updates or whole repository.

So I will implement the application to use the "newer" manifest wherever it is located, and an option to also look on GitHub and download/update directly from there without having to wait for a new build.

That is for the next beta 3 release.

When that is added, we can build towards this share-feature and how that can be.

My dream is to handle that in the app and make contributions from within the application, so you don't even need to have a git account and understand forking and pull requests. That way everyone could contribute to the same repository as well.

I'm also interested in people who can help out in the future with maintaining, accepting pull requests etc in the ProfileManifests repository as I will gladly share that with responsible admins. But again, the app is quite early and probably a few more things like this manifest-update feature need to be implemented. Aswell as more documentation on how things work before more people can invest in this. But that is absolutely the plan.

Now, this post is already quite long, but just to mention what @rodchristiansen said about sharing existing profiles. I see that as another big part where an admin can find working profiles for different settings and that is another type of community sharing that needs to be separated into different repositories etc. So to have that searchable in the app, something like the autopkg solution where the main repo is adding user repos as submodules to enable searching is the way to go. AND support for direct links would help when you need private repos or other repos not included in the "master" repo.

But i totaly agree, this is a feature that I will work towards. But first, the app needs some more core functions until this can be implemented, but it is definitely on the list.

**Comment by aschwanb** [comment]
You've clearly put a lot of thought into this feature and I agree with both your approach as well as your timeline.

Shall I leave this open as a place to discuss the implementation or do you want me to close it?

**Comment by apizz** [comment]
This is implemented via the ProfileManifests framework
